---
- hosts: all
  vars:
    app_root: '/home/deploy/app'
    app_user: deploy
    app_public: "{{app_root}}/current/public"
    roles_path: 'provisioner/roles'

  roles:
    # - "{{roles_path}}/init"
    # - "{{roles_path}}/ruby"
    # - "{{roles_path}}/nodejs"
    # - "{{roles_path}}/sqlite3"
    # - "{{roles_path}}/python-tools"
    # - "{{roles_path}}/mongodb"
    # - "{{roles_path}}/unicorn"
    - "{{roles_path}}/nginx"
    # - "{{roles_path}}/puma"

  tasks:

    # - name: Install language support packages
    #   sudo: yes
    #   apt: pkg={{ item }} state=latest
    #   with_items:
    #     - pkg-config
    #     - link-grammar
    #     - liblink-grammar4
    #     - link-grammar-dictionaries-en


    # - name: Run bundler
    #   command: bash -lc "cd {{ project_root }} && bundle install"
