---
- hosts: all
  vars:
    app_root: '/vagrant'
    app_user: vagrant
    app_public: "{{app_root}}/public"
    roles_path: 'provisioner/roles'

  roles:
    - "{{roles_path}}/init"
    - "{{roles_path}}/ruby"
    - "{{roles_path}}/nodejs"
    - "{{roles_path}}/sqlite3"
    # - "{{roles_path}}/python-tools"
    # - "{{roles_path}}/mongodb"
    - "{{roles_path}}/puma"
    - "{{roles_path}}/nginx"

  tasks:

    # - name: Install language support packages
    #   sudo: yes
    #   apt: pkg={{ item }} state=latest
    #   with_items:
    #     - pkg-config
    #     - link-grammar
    #     - liblink-grammar4
    #     - link-grammar-dictionaries-en


    - name: Run bundler
      command: bash -lc "cd {{ app_root }} && bundle install"
